# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/
relative_permalinks: false

# Setup
title:               optd-dl
tagline:             'A Jekyll theme'
description:         ''
url:                 http://optd-dl.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              optd
  url:               http://open.rongcapital.cn
  email:             optd-dl@ruixuesoft.com

# Custom vars
version:             1.0.0
